version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    restart: always

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env   
    environment:
      - NODE_ENV=development
    restart: always
